# Generated by Django 2.0 on 2018-08-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='location',
            field=models.TextField(default='mylocationdefault', max_length=100),
        ),
    ]
