# Generated by Django 2.0 on 2018-08-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profiles_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='job',
            field=models.TextField(default=2, max_length=120),
            preserve_default=False,
        ),
    ]
