# Generated by Django 2.0 on 2018-08-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profiles_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='job',
            field=models.TextField(default=False, max_length=120),
        ),
    ]
