# Generated by Django 2.1 on 2018-08-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_albums_songs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=120)),
                ('album_title', models.TextField(max_length=120)),
                ('genre', models.TextField(default='mylocationdefault', max_length=100)),
                ('album_logo', models.ImageField(blank=True, max_length=120, upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='songs',
            new_name='Song',
        ),
        migrations.DeleteModel(
            name='albums',
        ),
    ]
