# Generated by Django 2.1 on 2018-08-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20180825_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(default='mylocationdefault', max_length=100),
        ),
    ]
