# Generated by Django 2.1 on 2018-08-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20180828_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='name',
            new_name='song',
        ),
    ]
