# Generated by Django 2.1 on 2018-08-30 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20180830_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.Album'),
        ),
    ]
