# Generated by Django 2.1 on 2018-08-30 16:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20180830_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='albums',
        ),
        migrations.RemoveField(
            model_name='song',
            name='albums',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default='identity', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Album'),
        ),
        migrations.AddField(
            model_name='song',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
