# Generated by Django 2.1 on 2018-09-05 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_remove_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default='identity', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Album'),
        ),
        migrations.AddField(
            model_name='song',
            name='userId',
            field=models.IntegerField(default=None),
        ),
    ]
