# Generated by Django 2.1 on 2018-09-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20180905_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='titleDeed',
            fields=[
                ('owners_name', models.CharField(max_length=30)),
                ('ref_no', models.CharField(max_length=25)),
                ('demographic', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=20)),
            ],
        ),
    ]
