# Generated by Django 2.1 on 2018-09-06 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_titledeed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=120)),
                ('genre', models.TextField(max_length=120)),
                ('producer', models.TextField(default='mylocationdefault', max_length=100)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Album')),
            ],
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
