# Generated by Django 2.1 on 2018-09-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20180906_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songmodel',
            name='album',
        ),
    ]
