# Generated by Django 2.1 on 2018-09-06 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_auto_20180907_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='song',
            name='userId',
        ),
    ]
